"""Added votes and hasVoted Columns with Integer data types

Revision ID: a265dd6c28fd
Revises: e569e06b877e
Create Date: 2018-06-17 13:15:23.253912

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a265dd6c28fd'
down_revision = 'e569e06b877e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('hasVoted', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'hasVoted')
    # ### end Alembic commands ###
