"""Added Votes attribute for each user

Revision ID: e569e06b877e
Revises: 9b152e583304
Create Date: 2018-06-08 18:06:00.758583

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e569e06b877e'
down_revision = '9b152e583304'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('votes', sa.Numeric(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'votes')
    # ### end Alembic commands ###
